# Generated by Django 4.0.1 on 2022-01-31 07:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=255)),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment_on_which_user_can_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_object', to='SB.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SBUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('date_of_birth', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('your_first_school', models.CharField(blank=True, max_length=255, null=True)),
                ('your_college', models.CharField(blank=True, max_length=255, null=True)),
                ('your_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('your_address', models.CharField(blank=True, max_length=255, null=True)),
                ('favourite_movies', models.CharField(blank=True, max_length=255, null=True)),
                ('favourite_books', models.CharField(blank=True, max_length=255, null=True)),
                ('tell_your_friends_about_you', models.TextField(blank=True, max_length=500, null=True)),
                ('display_email', models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], max_length=255)),
                ('display_mobile', models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], max_length=255)),
                ('display_personal_info', models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], max_length=255)),
                ('display_friends', models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], max_length=255)),
                ('who_can_comment', models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(to='SB.SBUser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('number_of_likes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SB.post')),
                ('sbuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SB.sbuser')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='sbuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SB.sbuser'),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('number_of_likes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SB.comment')),
                ('sbuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SB.sbuser')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SB.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sbuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SB.sbuser'),
        ),
    ]
