# Generated by Django 4.0.1 on 2022-01-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbuser',
            name='display_email',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], default='Public', max_length=255),
        ),
        migrations.AlterField(
            model_name='sbuser',
            name='display_friends',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], default='Public', max_length=255),
        ),
        migrations.AlterField(
            model_name='sbuser',
            name='display_mobile',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='sbuser',
            name='display_personal_info',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], default='Public', max_length=255),
        ),
        migrations.AlterField(
            model_name='sbuser',
            name='who_can_comment',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], default='Public', max_length=255),
        ),
    ]
