# Generated by Django 4.0.1 on 2022-02-02 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0002_alter_like_options_likedorcommentedposts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented_at']},
        ),
    ]
