# Generated by Django 4.0.2 on 2022-02-08 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0002_alter_favouritefield_field_alter_userinterest_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_field', to='SB.favouritefield')),
                ('pages', models.ManyToManyField(blank=True, related_name='field_pages', to='SB.Page')),
            ],
        ),
    ]
