# Generated by Django 4.0.2 on 2022-02-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=500)),
                ('posts', models.ManyToManyField(blank=True, related_name='tagged_posts', to='SB.Post')),
            ],
        ),
    ]
