# Generated by Django 4.0.2 on 2022-02-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0003_post_page_post_tags_alter_sbuser_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='commented_posts', to='SB.Comment'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='SB.Like'),
        ),
    ]
