# Generated by Django 4.0.2 on 2022-02-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0003_fieldpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbuser',
            name='favourite_fields',
            field=models.ManyToManyField(related_name='user_favourite_fields', to='SB.FavouriteField'),
        ),
    ]
