# Generated by Django 4.0.1 on 2022-02-01 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0003_remove_comment_sbuser_remove_commentlike_sbuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlike',
            name='number_of_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_comments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
