# Generated by Django 4.0.2 on 2022-02-05 15:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0004_userinterest_comments_userinterest_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number_of_shares',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='post',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sharing_post', to='SB.post'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='shares',
            field=models.ManyToManyField(blank=True, related_name='shares', to='SB.Post'),
        ),
    ]
