# Generated by Django 3.2.12 on 2022-02-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0004_alter_sbuser_favourite_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='posts_to_be_suggested',
            field=models.ManyToManyField(blank=True, related_name='to_be_suggested_posts', to='SB.Post'),
        ),
        migrations.AlterField(
            model_name='sbuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_SB_sbuser_friends_+', to='SB.SBUser'),
        ),
    ]
