# Generated by Django 3.2.12 on 2022-02-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0005_auto_20220227_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinterest',
            name='suggested_posts',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='suggested_posts',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
