# Generated by Django 4.0.2 on 2022-02-05 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0005_post_number_of_shares_post_shared_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number_of_likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='post',
            name='effective_number_of_comments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_comments',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_likes',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
