# Generated by Django 4.0.1 on 2022-02-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0006_comment_likes_comment_number_of_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sbuser',
            name='who_can_comment',
        ),
        migrations.AddField(
            model_name='post',
            name='who_can_comment',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], default='Public', max_length=255),
        ),
    ]
