# Generated by Django 4.0.2 on 2022-02-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0006_comment_number_of_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='number_of_followers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
