# Generated by Django 3.2.12 on 2022-02-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0006_auto_20220227_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='suggested_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='userinterest',
            name='suggested_posts',
        ),
        migrations.AddField(
            model_name='userinterest',
            name='suggested_posts',
            field=models.ManyToManyField(blank=True, related_name='suggested_posts', to='SB.Post'),
        ),
    ]
