# Generated by Django 4.0.1 on 2022-02-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0007_remove_sbuser_who_can_comment_post_who_can_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='who_can_see',
            field=models.CharField(choices=[('Public', 'Public'), ('Friends', 'Friends'), ('None', 'None')], default='Public', max_length=255),
        ),
    ]
