# Generated by Django 3.2.12 on 2022-02-28 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0007_auto_20220227_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='profiles_suggested_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 5, 3, 32, 581050, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinterest',
            name='profiles_to_be_suggested',
            field=models.ManyToManyField(blank=True, related_name='to_be_suggested_profiles', to='SB.Page'),
        ),
    ]
