# Generated by Django 4.0.1 on 2022-02-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0008_post_who_can_see'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sbuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='SB.SBUser'),
        ),
    ]
