# Generated by Django 3.2.12 on 2022-02-28 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SB', '0008_auto_20220228_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinterest',
            name='pages_suggested_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 10, 47, 47, 902384, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinterest',
            name='pages_to_be_suggested',
            field=models.ManyToManyField(blank=True, related_name='to_be_suggested_pages', to='SB.Page'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='suggested_pages',
            field=models.ManyToManyField(blank=True, related_name='suggested_pages', to='SB.Page'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='suggested_profiles',
            field=models.ManyToManyField(blank=True, related_name='suggested_profiles', to='SB.SBUser'),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='profiles_to_be_suggested',
            field=models.ManyToManyField(blank=True, related_name='to_be_suggested_profiles', to='SB.SBUser'),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='suggested_at',
            field=models.DateTimeField(),
        ),
    ]
